### ISSUE TITLE
Lists of ads per section

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/saturn-theme#101]
We need different to support different list of ads depending on the section. For example, sections could be:
 - latest
 - categories
 - tags
 - post
 - media
 - default

It should be designed in a way that if there's a list for that type of content, the list is used, and if not, default is used.

This is a possible new implementation of the object:

```json
[
  {
    "type": "latest",
    "formats": [ ... ]
  },
  {
    "type": [ "category", "tag" ],
    "formats": [ ... ]
  },
  {
    "type": "post",
    "formats": [ ... ]
  },
  {
    "type": "media",
    "formats": [ ... ]
  },
  {
    "formats": [ ... ] // DEFAULT
  }
]
```

**Comment by orballo** [comment]
Client configs:
- [ ] DMC
- [ ] AZTV
- [ ] AA
- [ ] HNet
- [ ] WPD
- [ ] VS
