### ISSUE TITLE
Custom content on iFrame

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/saturn-theme#104]
Somehow, we have to add the possibility to add iframes with custom content and position it in different places of the page.

**Comment by luisherranz** [comment]
Blocked until they give us the iframe url.

**Comment by Poliuk** [comment]
More info provided by the customer: 

> Para la ubicación de los iframes, la cosa es bastante sencilla:
>
> - Iframe de espacios de marca: en la home y sus paginaciones, a media altura (si hay 10 artículos, después del 5)
> - Iframe de mini fichas en artículos: en todos los artículos, al final del contenido.

**Comment by Poliuk** [comment]
**unblocked** 

The customer has provided this information:

> -  https://www.diariomotor.com/espacio-ford/home_export_17_feed.html 
> - hasta 400px de anchura (debería cubrir todos los móviles) tiene 465px de altura y hasta 800px (debería cubrir los tablets) tiene 400px de altura. Si hubiera que ajustar algún detalle lo vemos luego, podemos probar así.
> - Has to appear after the third article in the home list.

**Comment by DAreRodz** [comment]
Closes at 66e88f2890cb509f0356d5ebb2a7b286abe2f30b and https://github.com/wp-pwa/wp-pwa/commit/262eaaee5c79cc20e517b33ab062f15a8d17181a.
