### ISSUE TITLE
Extra dimensions to GA and GTM

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/saturn-theme#106]
They are going to implement a new field in the API with this type of structure:

```js
...
custom_analytics: {
  dimension1: "xxx",
  dimension2: "aa/mm/yy",
  dimension3: "zzz"
},
...

```

And if present that should be sent with the virtualPageview of GTM or the pageview of GA.

**Comment by luisherranz** [comment]
Blocked until they implement it

**Comment by Poliuk** [comment]
Their solution is live on their site. 

Can be seen here for example: https://peta.diariomotor.com/competicion/?rest_route=/wp/v2/post/57790

```json
"custom_analytics": {
    "dimension1": "humberto",
    "dimension2": "2017-01-02",
    "dimension4": "post"
}
```

**Comment by orballo** [comment]
Blocked by #159

**Comment by orballo** [comment]
This issue will be fixed in https://github.com/wp-pwa/wp-pwa/issues/59, because `saturn-theme` is no longer the right repo for it.
