### ISSUE TITLE
Send GA and GTM events when share is used

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/saturn-theme#107]

**Comment by Poliuk** [comment]
@luisherranz could this be a good opportunity to send "everything" as an action to our own google analytics?

**Comment by luisherranz** [comment]
Yes. We should sit down and decide an event schema.

**Comment by orballo** [comment]
List of elements:
- [ ] Open menu
- [ ] Close menu
- [ ] Open share modal on List
- [ ] Close share modal on List
- [ ] Open share modal on Post
- [ ] Close share modal on Post
- [ ] Close cookies modal
- [ ] Open comments
- [ ] Close comments
- [ ] Each share button on share modal
- [ ] Echa share button on share bar
- [ ] Next button
- [ ] Swipe in categories
- [ ] Swipe in post
- [ ] Notifications button on bar
- [ ] Notifications button on menu
- [ ] Category links on bar
- [ ] Category links on menu
- [ ] Infinite scroll triggered (Post)
- [ ] Load more triggered (List)
- [ ] Clicked on Logo
