### ISSUE TITLE
Add home (latest posts) below post on SSR

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/saturn-theme#108]

**Comment by orballo** [comment]
Blocked by #34

**Comment by orballo** [comment]
@DAreRodz this issue is related to the one about infinite scrolling.

**Comment by orballo** [comment]
- [ ] Add new analytics event to docs.

**Comment by luisherranz** [comment]
Moved to https://github.com/frontity/saturn-theme/issues/6
