### ISSUE TITLE
Fix transparent images

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/saturn-theme#112]
When the featured image is transparent, the img placeholder is visible. 

![Screen Shot 2018-02-05 at 19.36.47.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58b46c76cb082b1a00bab064/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216454f66b7191a379e60c2857415b49be5d4a1f06a3a3dc78e2a436628f0d0defd16d0d7cc03a43fdeb8a1fbf00ec76dd4a81e5bd9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec95ffe4ee44552a01b3261f43b.png)

> https://blog.worona.org/push-notifications-starter-pro-theme-are-here/

**Comment by luisherranz** [comment]
Moved to https://github.com/frontity/saturn-theme/issues/7
