### ISSUE TITLE
Fix autoplay from LazyVideo

### ISSUE THREAD

**Issue by orballo** [wp-pwa/saturn-theme#114]
If a HTML5 video is loaded in a sibling slide, the autoplay starts the video and the user can't find where the video is playing to stop it.

We should either fix the load of this video on the sibling or remove autoplay.

**URL:**

https://herencia.net/2018-02-06-carnaval-informativos-regional-tve1/

**Screenshot:**

![screenshot 2018-02-06 13 11 43](https://user-images.githubusercontent.com/13615057/35859164-4fabfb52-0b3f-11e8-8ee5-c77b7fccfd5f.png)

**Reproduce:**

Get into the previous post from the list and the video will render in the next slide, starting to play.

**Comment by orballo** [comment]
This has been solved in #119

**Comment by luisherranz** [comment]
@orballo, we need to respect the original autoplay setting of the HTML. Reopening.
