### ISSUE TITLE
Going directly to a taxonomy which is not on the menu redirects to home

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/saturn-theme#12]
For example:
https://demo.worona.test/wp-cat/travel/

**Comment by luisherranz** [comment]
To solve this, we are going to add the selected as the first item of the context if it is not present in the context. We will maintain the same generator so we can move back and forth like we were in that context.

**Comment by DAreRodz** [comment]
Closed at https://github.com/wp-pwa/wp-org-connection/commit/444b0cd95f317d3cc65a66af899fe3190b07e86a.
