### ISSUE TITLE
Category menu is over post title in AMP

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/saturn-theme#146]
![Screen Shot 2018-02-20 at 11.15.24.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58af0e4ea157412000799534/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216456f36b7191a379ee0c2a54415d4abe5d4a1f06a3a3dc78e2a436628f0d0defd16d0d7cc03a43fdeb8a1fbf00ec76dd4a81e5bd9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec951f749e04a5ca7143561f43b.png)

**Comment by luisherranz** [comment]
@orballo let me know once it's done and I'll push it to production

**Comment by orballo** [comment]
@luisherranz Issue fixed.

**Comment by luisherranz** [comment]
Awesome, thanks @orballo !
