### ISSUE TITLE
Links in preformatted texts are not visible

### ISSUE THREAD

**Issue by rmartinezduque** [wp-pwa/saturn-theme#149]
You can see an example at the bottom of this post, where it says "Featured image...": https://blog.worona.org/ux-designing-tips-to-improve-conversion-rates/

![link-preformatted-text.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58e3c98213b6b5001a7ac226/125516c66e82c728ace21e0d46e49d9428cf93bb8aefb051a95ce4802c426a672c1cb7693cc7f33ab0487e021b4d44be44095946fcf9db23a0b16e21d9540bedd03b0922c33942adaa9e0dfd50e474d412dcfce9c85ecafa3c22ed8a8a4e371f011d8bfa5d3ca2915985.png)

**Comment by luisherranz** [comment]
Moved to https://github.com/frontity/saturn-theme/issues/10
