### ISSUE TITLE
Add RTL support

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/saturn-theme#153]
blogs written in arabic language should support RTL orientation

**Comment by Poliuk** [comment]
@orballo example: https://www.nmisr.com

**Comment by orballo** [comment]
List of elements that should be changed because of RTL:

- [ ] Content
- [ ] Carousel
- [ ] Post Header
- [ ] Navbar
- [ ] Cookies should not be loaded (probably)
- [ ] Post Tag List
- [ ] Share Bar
- [ ] Share Modal
- [ ] Swipe direction
- [ ] Menu
- [ ] Dots animation direction

**Comment by luisherranz** [comment]
Moved to https://github.com/frontity/saturn-theme/issues/11
