### ISSUE TITLE
Ads over content

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/saturn-theme#157]
It happens when going directly to this url:
https://viviendosanos.com/la-zanahoria-bronceado-natural/

It didn't happen in the previous deploy:
https://viviendosanos.com/la-zanahoria-bronceado-natural/?server=https://wp-pwa-obvpzudldn.now.sh

So it was introduced in saturn 1.1.1.

**Comment by orballo** [comment]
This bug has disappeared after some changes in the media converter, but it hasn't been properly solved.

**Comment by orballo** [comment]
Ads current behavior is as expected, so I'm closing this issue.

The content render issue will be addressed with a more deep refactoring in #158 in the future.
