### ISSUE TITLE
Send events to GA everytime someone shares a post

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/saturn-theme#160]
Send events to GA everytime a post is shared using the share buttons. 

> blocked by https://github.com/wp-pwa/saturn-theme/issues/161

**Comment by orballo** [comment]
@Poliuk 
They are being sent with the event action `PWA - share`.
The event category might be `PWA - Share bar` or `PWA - Share modal` depending on the component used.
The event label will contain the `method` used for share (Facebook, email...), `type` of content (post, page...) and the `context` or view in which the action took place (Post, Media, List...).
