### ISSUE TITLE
Cancel bouncerate when the user interacts with the PWA

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/saturn-theme#161]
We have to send events to our customers' GA everytime the user interacts with the PWA.

It would be cool if we can reuse the events of #107, instead of having two different codes for this.

**Comment by DAreRodz** [comment]
blocked by #55 and #159

**Comment by orballo** [comment]
I'm unblocking this!

**Comment by orballo** [comment]
We have to decide prefix/names in event categories/actions for clients to identify them as Frontity events.

**Comment by orballo** [comment]
Categories and actions will be prefixed with `PWA -`.
