### ISSUE TITLE
Post not showing up on PWA

### ISSUE THREAD

**Issue by rmartinezduque** [wp-pwa/saturn-theme#162]
This post (https://2018.europe.wordcamp.org/2018/01/31/meet-the-media-partners-and-supporters/) is not showing up on the PWA (https://ssr.wp-pwa.com/?siteId=7HPcSP8pXXh4ECq6P&env=prod)

**Comment by DAreRodz** [comment]
Fixed at https://github.com/wp-pwa/saturn-theme/commit/dee3d48351557c733103d544708e22fcc65ac9cd.
