### ISSUE TITLE
Cookies notification doesn't show on AMP in Safari

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/saturn-theme#168]
It looks like it has to do with the css, because if you remove the current css it starts showing again.

**Comment by orballo** [comment]
Fixed in #173

**Comment by Poliuk** [comment]
*reopening* @orballo I'm not able to see the cookies modal

**Comment by luisherranz** [comment]
You can check this url:
https://origin.amp.wp-pwa.com/goodbye-mobile-apps-hello-progressive-web-apps/?siteId=PHAzpvws5pvZw7XuW&env=prod&singleType=post&singleId=2766&initialUrl=https://blog.worona.org/goodbye-mobile-apps-hello-progressive-web-apps/
