### ISSUE TITLE
AMP - Hojas de estilo CSS no válidas (problema Importante)

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/saturn-theme#170]
**Detalles:**	
No se permite la etiqueta "font".

**URL de AMP:**	
https://amp.herencia.net/2007-08-23-herencia-amanece-sin-agua-corriente/?siteId=uTJtb3FaGNZcNiyCb&env=prod&singleType=post&singleId=794&initialUrl=https://herencia.net/2007-08-23-herencia-amanece-sin-agua-corriente/

**URL canónica:**	
https://herencia.net/2007-08-23-herencia-amanece-sin-agua-corriente/

**código**
```html
<p><font size="1"><em>La fotografía ha sido extraída de miciudadreal.es ya que no hemos localizado ningún logo de Emaser.</em></font></p><div class="css-oivwps css-19i9r5m0"><amp-ad type="adsense" data-ad-client="ca-pub-2096136633140656" data-ad-slot="5968880319" layout="fill"></amp-ad></div>
``` 
_line 23_

**Comment by DAreRodz** [comment]
Fixed at https://github.com/wp-pwa/wp-pwa-plugin/commit/c322c331d575d76800d8e99d5dbc3855ae0da113.
