### ISSUE TITLE
scrollable menu glitch on AMP

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/saturn-theme#181]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/2798729/37358333-1a053262-26eb-11e8-8d9e-ea60de189500.gif)

When accessing to the AMP version of a post served by google the scrollable menu glitches.

**URL _(searching `worona install amp`)_** https://www.google.es/amp/s/amp.wp-pwa.com/add-google-amp-wordpress-site/%3FsiteId%3DPHAzpvws5pvZw7XuW%26env%3Dprod%26singleType%3Dpost%26singleId%3D2671%26initialUrl%3Dhttps://blog.worona.org/add-google-amp-wordpress-site/

The glitch doesn't happen when you enter directly to the AMP link: https://amp.wp-pwa.com/add-google-amp-wordpress-site/?siteId=PHAzpvws5pvZw7XuW&env=prod&singleType=post&singleId=2671&initialUrl=https://blog.worona.org/add-google-amp-wordpress-site/

**Comment by orballo** [comment]
@Poliuk Wow! that's how you write an issue! :+1:

**Comment by orballo** [comment]
Steps:

In iOS simulator search in google for `blog.worona.org keys`
