### ISSUE TITLE
Incorrect Page Title. Displaying "Frontity Site"

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/saturn-theme#182]
**Site** [wanerd.com](https://wanerd.com)

conflict with site-info:

_connection siteinfo_
![screen shot 2018-03-13 at 19 22 02](https://user-images.githubusercontent.com/2798729/37361876-34b1a0ba-26f4-11e8-9829-bba0f11e06fe.png)

_endpoint siteinfo_
![screen shot 2018-03-13 at 19 20 57](https://user-images.githubusercontent.com/2798729/37361890-38c28c5a-26f4-11e8-9e7c-8c257f830108.png)

**Comment by orballo** [comment]
Fixed with a redeploy.
