### ISSUE TITLE
cannot read property "_link" of undefined

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/saturn-theme#184]
AMP is not working properly in `wanred.com`

*LINK:* https://amp.wp-pwa.com/samsung-galaxy-a8-2018-actualizacion-marzo/?siteId=xGXtTXQtonv3T8m3K&env=prod&dev=false&singleType=post&singleId=5139&initialUrl=/samsung-galaxy-a8-2018-actualizacion-marzo/

**Comment by luisherranz** [comment]
https://localhost:3000/?siteId=xGXtTXQtonv3T8m3K&env=prod&dev=false&singleType=post&singleId=5139&initialUrl=/samsung-galaxy-a8-2018-actualizacion-marzo/

**Comment by orballo** [comment]
Fixed in https://github.com/wp-pwa/saturn-theme/commit/1a923c542d244c58273c69ba403997779bb95d5e
