### ISSUE TITLE
Dynamic height for ads

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/saturn-theme#196]
It looks like the PWA needs to support dynamic heights for the ads.

**Comment by DAreRodz** [comment]
With the changes in commit wp-pwa/wp-pwa@2396fe931da2bd7b07485afc8d0a62ba653ee18f, Smart Adserver ads can have a dynamic height, working the `height` property as the minimum height for the ad.

For the height to be dynamic, you need to use the `callType` property with the `std` value (it doesn't work with the `iframe` value).
