### ISSUE TITLE
change "navbar" to async mode again

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/saturn-theme#216]
The navbar is not working properly after scrolling down and up a few times inside the post view.

**Comment by luisherranz** [comment]
@Poliuk are you sure about this?

**Comment by Poliuk** [comment]
I think it would be interesting to see the consequences of making it "synchronous".

Because right now, the behavior feels a bit buggy as it appears and disappears with a random delay. I think it's important to give a consistent experience, so the user learns that the navbar always appears and disappears under the same circumstances. 

So let's see what happens with the rest of the performance if we make the navbar synchronous.
