### ISSUE TITLE
iFrame in iOS is huge

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/saturn-theme#219]
The space of the iframe in iOS is way bigger than the iFrame itself.

**Comment by DAreRodz** [comment]
Fixed at https://github.com/wp-pwa/wp-pwa/commit/15bcd30791e5724baf272b70f2e68051d81b7900

**Comment by luisherranz** [comment]
@DAreRodz what was the problem?

**Comment by DAreRodz** [comment]
@luisherranz  It's a bug on iOS that resizes iframes to the full size of their content. I used a workaround with CSS to avoid this and now it's working in Chrome and Safari iOS.

**Comment by luisherranz** [comment]
Good to know! Thanks.
