### ISSUE TITLE
Galleries still not working in DM Competición

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/saturn-theme#236]
Check if the galleries are broken because of a bug in the rest API or because of our implementation. 

Their API was sending an invalid HTML (with a double quote): ` class=“gallery-regular” ”`

**URL:** https://peta.diariomotor.com/competicion/noticia/kamaz-4326-diez-toneladas-y-1-000-cv-volando-sobre-la-nieve/?force=true&server=https://pressr.wp-pwa.com

**Comment by Poliuk** [comment]
blocked by https://github.com/wp-pwa/wp-pwa-plugin/issues/56

**Comment by luisherranz** [comment]
We have to create a plugin for them. I'm on it now.

**Comment by luisherranz** [comment]
Blocked until they find out what hook are they using

**Comment by luisherranz** [comment]
Unblocked and assigned to @DAreRodz

**Comment by DAreRodz** [comment]
Closed at fb7076ccb6472478b53836a62987d76f0e4f6e68.
