### ISSUE TITLE
Increase space between banners

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/saturn-theme#238]
DM has asked to increase the space between banners in the post list. 

Check their mobile version of www.diariomotor.com to see how we can copy the ads layout using our current options.

**Comment by orballo** [comment]
"We need to enable a new position for megabanners on top of the lists. Megabanners have different heights (300x50, 300x75, 300x100), so we need to fix them to 100px until we have resizable iframes for the ads." (from #242)

**Comment by DAreRodz** [comment]
Closed at https://github.com/wp-pwa/saturn-theme/commit/d21a46e8991dc0c6f2dc9e1eb66eeaffc99cea80 and https://github.com/wp-pwa/wp-pwa/commit/e6f5fdc09f56c322423651e7c180eca6fc8f024e
