### ISSUE TITLE
Configure the author to appear at the beginning of the posts

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/saturn-theme#241]
DM has asked to move back to the top the "Author" info.

**Comment by orballo** [comment]
Set up in the database.

**Comment by luisherranz** [comment]
@orballo is this supposed to be already set up, or did you mean we *have to* set it up on the database?

**Comment by orballo** [comment]
This was done in the peta db.

**Comment by luisherranz** [comment]
My bad, I saw the date on the bottom and I thought it was not working. Sorry about that.

Does it make sense that the author is on the top and the date is on bottom? @Poliuk what do you think? Did they request it like that? Maybe we should put the date on the same line than the author.

**Comment by Poliuk** [comment]
@luisherranz @orballo The issue was not 100% clear, so my apologies for this. Let's see if they ask us to put everything together again. If not, I would wait until we start with the redesign to decide about this.

**Comment by luisherranz** [comment]
Ok

**Comment by orballo** [comment]
Oki doki

**Comment by Poliuk** [comment]
I'm reopening this issue. `DM` has asked to put the date together with the author.

**Comment by orballo** [comment]
Ok

**Comment by orballo** [comment]
Set up done for production.
