### ISSUE TITLE
Remove sticky megabanner

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/saturn-theme#242]
DM is not going to use the sticky megabanner.  Instead, they want to use a megabanner at the beginning of the post lists. 

We need to enable a new position for megabanners on top of the lists. Megabanners have different heights (300x50, 300x75, 300x100), so we need to fix them to 100px until we have resizable iframes for the ads.

Probably related with the work going on #238

**Comment by orballo** [comment]
Removed sticky ads in database.
