### ISSUE TITLE
Invalid value for attribute in AMP tag 'controls' in tag 'amp-video'

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/saturn-theme#260]

**Comment by luisherranz** [comment]
@orballo is this solved?

If it's not, could you please recreate the issue in https://github.com/frontity/saturn-theme/issues?

**Comment by orballo** [comment]
I don't know, but if nobody complained I'd dare to say is fixed. Do you know any site with native videos to check it?

**Comment by luisherranz** [comment]
Ok, let's leave it for now then.
