### ISSUE TITLE
Carrousel showing up next column on swipe

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/saturn-theme#262]
Go to a carrousel:
![Screen Shot 2018-04-30 at 12.23.58.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58af0e4ea157412000799534/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276457f36b7191a379ed0c2952415a46be5d4a1f06a3a3dc78e2a436628f0d0defd16d0d7cc03a43fdeb8a1fbf00ec76dd4a81e5bd9850d2aa6c7bb3d4d216744b470a83ed5f35aa984eca5df643e2455ca7173064f43b.png)
Stop and swipe:
![Screen Shot 2018-04-30 at 12.24.11.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58af0e4ea157412000799534/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276457f36b7191a379ed0c2955415e4fbe5d4a1f06a3a3dc78e2a436628f0d0defd16d0d7cc03a43fdeb8a1fbf00ec76dd4a81e5bd9850d2aa6c7bb3d4d216744b470a83ed5c32aa984eca5df643e24454a510306bf43b.png)

**Comment by orballo** [comment]
https://androidayuda.com/2018/04/30/messenger-kids-modo-sueno/

**Comment by luisherranz** [comment]
Won't fix for the moment.
