### ISSUE TITLE
<title> can contain HTML

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/saturn-theme#263]
For example, here:
https://demo.worona.org/iceland/

**Comment by DAreRodz** [comment]
Using [`he.decode`](https://github.com/mathiasbynens/he#hedecodehtml-options)  because of https://github.com/nfl/react-helmet/issues/323.

**Comment by DAreRodz** [comment]
Also unexpected html tags are removed using a regexp. See 72aa64b9a0c0b0ba42c49dc548239027df00cf66.
