### ISSUE TITLE
Custom dimensions not working properly in attachments

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/saturn-theme#265]
Custom dimensions not being sent in attachements

**Comment by luisherranz** [comment]
I think they mean "media" (galleries)

**Comment by luisherranz** [comment]
The pageview is sent but without the custom dimensions:
![Screen Shot 2018-05-03 at 10.30.11.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58af0e4ea157412000799534/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266454f06b7191a379ef0c2851415e4fbe5d4a1f06a3a3dc78e2a436628f0d0defd16d0d7cc03a43fdeb8a1fbf00ec76dd4a81e5bd9850d2aa6c7bb3d4d216744b470a83ed5c3daa984eca5df548e74f56a0133164f43b.png)

**Comment by orballo** [comment]
Ok. I'll check it out.

**Comment by orballo** [comment]
I don't see any custom analytics in this media: https://peta.diariomotor.com/competicion/wp-json/wp/v2/noticias/72832/

Do you know any media that has custom analytics to see what is wrong?

**Comment by luisherranz** [comment]
It seems like they haven't included `custom_dimensions` in the media responses of the WP-API. They are informed, so closing this now.

Thanks @orballo!

**Comment by luisherranz** [comment]
Reopened because now media has `custom_dimensions` but they are not populated in `stores.analytics.customDimensions`.

**Comment by orballo** [comment]
It's working.
