### ISSUE TITLE
Issue with the galleries

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/saturn-theme#267]
The only pictures accessible are those linked from the parent article. The rest of the photos are not accessible in the gallery.

**URL:** https://www.diariomotor.com/competicion/noticia/el-campeonato-de-supercars-australiano-ya-se-imagina-como-sera-el-ford-mustang-2019/

**Comment by luisherranz** [comment]
I'm afraid the rest of the gallery is not on the WP-API.

**Comment by luisherranz** [comment]
Confirmed, the rest of the images are not in the HTML code.

**Comment by luisherranz** [comment]
We can solve it adding a link to the rest of the gallery, like the do in their desktop version. So the `process` which converts this gallery to native should also add a link from this div:

```html
<div class="gallery_regular_see_more_photos"><a href="https://www.diariomotor.com/competicion/noticia/el-campeonato-de-supercars-australiano-ya-se-imagina-como-sera-el-ford-mustang-2019/mustangrender5/" class="gallery-regular">Ver todas</a></div>
```

**Comment by luisherranz** [comment]
Blocked until they decide what to do

**Comment by luisherranz** [comment]
They are going to use native libraries.
