### ISSUE TITLE
Close button gets stuck between two contexts

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/saturn-theme#286]
If you go to a carrousel which creates a different context

**Comment by DAreRodz** [comment]
Fixed at https://github.com/wp-pwa/wp-org-connection/ebe8d35191e661f46a53be83f5451d08b61cb841

It was a problem with `history.go` function, that seems to be synchronous for the `MemoryHistory` implementation, but not so for the `BrowserHistory`implementation.
