### ISSUE TITLE
blank thumbnail at the end of a gallery

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/saturn-theme#290]
Check why there is a blank thumbnail at the end of the gallery. 

> **URL** https://www.diariomotor.com/competicion/noticia/dos-leyendas-de-porsche-que-quisieron-desafiar-al-infierno-verde-video/

**Comment by luisherranz** [comment]
Not fixed, it looks like a problem in PHP. Let's try updating the plugin to 1.4.8

**Comment by Poliuk** [comment]
@DAreRodz @luisherranz they have updated the plugin, but the blank thumbnail is still appearing. Should we reopen this issue?

**Comment by luisherranz** [comment]
@DAreRodz with the new version the image doesn't have an attachment id. We now have to filter gallery images without ids.
