### ISSUE TITLE
Display number of comments

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/saturn-theme#292]
Display the number of comments of a post before oppening the iframe. Check if the number is available in the REST API, or make it available inside every post if not. 

It looks like the disqus WordPress Plugin _"Syncs comments automatically to WordPress for backup and flexibility if you ever decide to switch to a different platform"_ so we can display directly the number stored inside WordPress.

> This feature should be an option.

**Comment by luisherranz** [comment]
Moved to https://github.com/frontity/saturn-theme/issues/13
