### ISSUE TITLE
Theme footer shows "powered by Worona"

### ISSUE THREAD

**Issue by DAreRodz** [wp-pwa/saturn-theme#302]
Change Worona logo by the new Frontity logo. This is the one that it's showing right now: https://worona-cdn.sirv.com/assets/worona%20icons/worona-logo-color.png?scale.width=100

**Comment by Poliuk** [comment]
@DAreRodz @orballo can any of you let me know if this new logo is okey to close this issue?

https://worona-cdn.sirv.com/logos/white-square.png
https://worona-cdn.sirv.com/logos/white-square%402x.png

Let's finish with the rebranding! haha

**Comment by luisherranz** [comment]
Yes, it's better if we upload a bigger one or even a svg.

**Comment by luisherranz** [comment]
Moved to https://github.com/frontity/saturn-theme/issues/20.
