### ISSUE TITLE
Bouncerate between AMP & PWA

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/saturn-theme#303]
It will be interesting to investigate and understand the behaviour of Google Analytics regarding the Bounce rate between AMP and PWA. 

Specifically, how does analyticis meassure a user that goes from the AMP version to the PWA, clicking inside the AMP version. Does it count as the same visit? Is there a way to unify `client ids`?

**Comment by luisherranz** [comment]
Moved to https://github.com/frontity/saturn-theme/issues/15
