### ISSUE TITLE
Cookie modal pops-up twice on Wanerd

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/saturn-theme#304]
blocked by https://github.com/wp-pwa/saturn-theme/issues/308

The cookies modal pops-up twice on Wanerd & iPadexperto. Only on iOS devices.

**Comment by orballo** [comment]
Waiting for #308 to be in production to check if there is still something wrong.

**Comment by rmartinezduque** [comment]
@luisherranz let me know when this is deployed. Thanks! (just mention me on this issue)

**Comment by luisherranz** [comment]
@rmartinezduque it looks like it's working now with the new library 👍
