### ISSUE TITLE
cookies modal not appearing

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/saturn-theme#306]
blocked by https://github.com/wp-pwa/saturn-theme/issues/308

The cookies modal is not popping-up in https://iosmac.es/ and it looks like it is configured properly in the db. 

Only if you go to "Opciones de privacidad" in the lateral menu and you close the window then the cookies pop-up appears. 

**Site Id** mEZfdocCWvFqzRHxm

**Steps to reproduce it**:

1. Go to https://iosmac.es/ and open the menu.
2. Click on "Opciones de privacidad" and then close that window.
![step1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58e3c98213b6b5001a7ac226/125516c66e82c728ace21e0d46fb809f33d3c1e5cdf9ad4cae58f3806b1c65262852f17b2087bb7ee8407a02575f4ead170e0941f8aa8839baa47e21d40854b088270a36d43703aeb9881eba03b32388468db3bd8e4bc2fa70.png)
![step2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58e3c98213b6b5001a7ac226/125516c66e82c728ace21e0d46fb809f33d0c1e5cdf9ad4cae58f3806b1c65262852f17b2087bb7ee8407a02575f4ead170e0941f8aa8839baa47e21d40854b088270a36d43703aeb9881eba03b32388468db3bd8e45c1fa70.png)
3. After closing the Privacy Policy the cookies pop-up shows up
![step3.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58e3c98213b6b5001a7ac226/125516c66e82c728ace21e0d46fb809f33d1c1e5cdf9ad4cae58f3806b1c65262852f17b2087bb7ee8407a02575f4ead170e0941f8aa8839baa47e21d40854b088270a36d43703adbf881eba03b32388468db3bd8945c2fa70.png)

**Comment by rmartinezduque** [comment]
@luisherranz let me know when this is deployed. Thanks! (just mention me on this issue, and I'll be notified ;) )

**Comment by luisherranz** [comment]
@rmartinezduque it looks like it's working now with the new library 👍
