### ISSUE TITLE
Author's name is not showing up

### ISSUE THREAD

**Issue by rmartinezduque** [wp-pwa/saturn-theme#307]
The author's name is not showing up in the posts of https://iosmac.es. The site ID of this site is mEZfdocCWvFqzRHxm.

Live example: https://iosmac.es/las-mejores-ofertas-del-dia-en-amazon-5.html

![No-author-name.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58e3c98213b6b5001a7ac226/125516c66e82c728ace21e0d46c69bd7229797a180fbf24da550f5d665043761260ea62864c7b96aea432d535f5f1ca4475f0d15aff1892ba7e06a268f5858ecc3714d36976345f3e5db55ea43a82a994e8dbcbd8f4ec9eb3e21e58d8a493f171755.png)

**Comment by luisherranz** [comment]
Authors are not available in its REST API:

![screen shot 2018-06-18 at 17 23 16](https://user-images.githubusercontent.com/3305402/41545831-5fddc10a-731c-11e8-8c99-3048daab4102.png)

He should disable his plugins until this error disappears:
https://iosmac.es/wp-json/wp/v2/users/86

My guess is that a "security" plugin is causing the issue.
