### ISSUE TITLE
Go back from classic version is not working

### ISSUE THREAD

**Issue by orballo** [wp-pwa/saturn-theme#330]
![Screenshot 2018-07-04 16.30.10.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6202d4f976d5001232e9d2/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6416703e7950e37a26cbb078f1132b43434d0eee1e020a17b8eb8339a3e73a728a5c59e5d76a0d25953511acb9d449e904be738a5d99a4fedb1294b7607caddecd5d340c041183fe5836a09e4acc5ef148e84b5db65e.png)

**Comment by luisherranz** [comment]
Moved to https://github.com/frontity/wp-plugin/issues/1
