### ISSUE TITLE
In List view, entering a post that is not first or second of its page forces a spinner in the next view

### ISSUE THREAD

**Issue by orballo** [wp-pwa/saturn-theme#331]
I think this is something related to the new context rendering the slider in index 0 and making a fast change to the proper index that is still not rendered.

**Comment by luisherranz** [comment]
@orballo can I move it to frontity/saturn-theme?

**Comment by orballo** [comment]
Yes you can.

**Comment by luisherranz** [comment]
Moved to https://github.com/frontity/saturn-theme/issues/17.
