### ISSUE TITLE
Implement "Infinite scrolling"

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/saturn-theme#34]
In the `post` screen, add the next article at the end so the user keeps reading. 

(only when post is visited from a list)

**Comment by DAreRodz** [comment]
Closed at 576f144f268cabb284030330110d2f303ed586fb. Additionally, a new component called RouteWaypoint was created in https://github.com/wp-pwa/wp-org-connection/commit/86b9e1c845914653bf6777bf4db022ee1c9f7cf8.

The infinite scrolling feature is currently working also for posts visited directly until the issue https://github.com/wp-pwa/saturn-theme/issues/108 is solved.
