### ISSUE TITLE
Make pagination URLS work

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/saturn-theme#41]
> **Hacer las URLs de paginación accesibles y funcionales en la versión Worona**

> Puede afectar a indexación. Aunque en adslzone.tv actualmente están desindexadas, sí llevan el atributo "follow" para seguir los enlaces. En otras webs es posible que estén indexadas. En cualquier caso, Google tiene esas URLs en su "lista" y las va a rastrear

> https://demo.worona.org/page/2/ no aparece referenciada en la versión Worona, y al abrirla carga la home sin tener en cuenta la página indicada

**Comment by Poliuk** [comment]
https://github.com/wp-pwa/saturn-theme/issues/35 will solve this issue

**Comment by luisherranz** [comment]
Closing this in favor of #35
