### ISSUE TITLE
Saturn for AMP

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/saturn-theme#42]
Theme:
- [x] Migrate AMP to new version
- [x] Cookies
- [x] Canonical

Post:
- [x] Image converter
- [x] Twitter converter
- [x] Instagram converter
- [x] Youtube converter
- [x] Video converter
- [ ] Carousel
- [x] Tags and categories.
- [x] Ads
- [ ] Comments (https://github.com/disqus/disqus-install-examples/tree/master/google-amp)
- [ ] Gallery

Top bar:
- [x] Logo
- [x] Menu button
- [x] Home button

Menu:
- [x] Logo
- [x] Close button
- [x] Links

Share:
- [x] Share buttons
- [x] Fix Facebook share.
- [x] Fix Pinterest share.
- [x] Next button
- [x] Native share

Review final code:
- [x] Decide what structure should be used for AMP in the project.
- [x] Clean dependencies (imports)
- [x] Clean props
- [x] Clean styles
- [x] Simplify duplicated code and components
- [x] Remove inline-styles (react-icons uses them)
- [x] Load all styles inside `<style amp-custom />`
- [x] Remove unnecesary styles
- [x] Remove not used AMP javascript

**Comment by luisherranz** [comment]
Everything need for AMP ready. Moved to AMP-2.
