### ISSUE TITLE
Add support for WP native galleries

### ISSUE THREAD

**Issue by DAreRodz** [wp-pwa/saturn-theme#52]

**Comment by luisherranz** [comment]
Include this [theme galleries](https://herencia.net/2018-01-18-encuentro-del-escritor-emilio-calderon-jovenes-los-centros-educativos-herencia/?force=true) as well.

**Comment by luisherranz** [comment]
Cannot be fully closed until https://github.com/wp-pwa/wp-pwa-plugin/issues/30 is done as well.

**Comment by Poliuk** [comment]
https://github.com/wp-pwa/wp-pwa-plugin/issues/30 is done and merged into `dev`. We can release a new version of the plugin including just this issue or wait until https://github.com/wp-pwa/wp-pwa-plugin/issues/31 is done. As you prefer :)
