### ISSUE TITLE
AdSense link units are limited to three

### ISSUE THREAD

**Issue by DAreRodz** [wp-pwa/saturn-theme#59]

**Comment by luisherranz** [comment]
Blocked until we decide how to deal with the problem.

**Comment by luisherranz** [comment]
My opinion would be to substitute by a normal ad with the same (or similar) size.

**Comment by DAreRodz** [comment]
Yes, maybe looking for the next ad with similar size in the ad list or defining a fallback inside the link unit's properties, like

```javascript
{
  "type": "adsense"
  "format": "link",
  // ...
  "fallback": {
    "type": "adsense"
    // ...
  }
}
```
