### ISSUE TITLE
Add GTM for clients

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/saturn-theme#66]
- [x] Add script
 - [ ] Send virtual pageviews with parameters

The second task is blocked until we receive the list of parameters from DM.

Multiple gtm clients:
https://developers.google.com/tag-manager/devguide?hl=en#multiple-containers

**Comment by DAreRodz** [comment]
Closed at https://github.com/wp-pwa/wp-pwa/commit/2ced3ea69e0cf0ed2ceb7a41b13ae163b89950d0.
