### ISSUE TITLE
Fix warning in (probably) Gallery component

### ISSUE THREAD

**Issue by orballo** [wp-pwa/saturn-theme#79]
You can see it when rendering on the server.

EDIT: https://viviendosanos.com/remedios-para-los-quistes-en-los-ovarios/

![screenshot 2018-01-24 18 37 37](https://user-images.githubusercontent.com/13615057/35347542-bcf2bd7c-0135-11e8-9d97-03e5d9b1c533.png)
![screenshot 2018-01-24 18 37 55](https://user-images.githubusercontent.com/13615057/35347543-bd14ed84-0135-11e8-9962-c8ad7dc99e20.png)

**Comment by luisherranz** [comment]
@orballo could you please tell the post where this problem appears?

**Comment by orballo** [comment]
Sure, sorry about that. It's https://viviendosanos.com/remedios-para-los-quistes-en-los-ovarios/
