### ISSUE TITLE
Classname undefined in WP Appbox

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/saturn-theme#82]
The bug can be reproduced going to the home of AA, then entering the `saber-redes-wifi-guardadas-android` post.

It looks like className can be undefined:
![screen shot 2018-01-25 at 09 49 09](https://user-images.githubusercontent.com/3305402/35379044-13d78166-01b5-11e8-9d15-174a0f69ccbe.png)

In this line:
https://github.com/wp-pwa/saturn-theme/blob/1fedf56872f8271e716777411ef05a8b0eb51c22/src/shared/converters/wpappbox.js#L12

**Comment by orballo** [comment]
Closed by 97b9b2c13375df4f725cb32e839a94828e7df8a9
