### ISSUE TITLE
Add "link color" option in theme

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/saturn-theme#84]
Add a "link color" and "link style" (bold, underline...) option to the theme and use it to style anchors (<a>) of content.

After that, configure AA like this:
![unnamed](https://user-images.githubusercontent.com/3305402/35438709-e717a1ae-0297-11e8-865d-62ceeb4fee28.png)

**Comment by luisherranz** [comment]
For example, it could be like this:
```js
linkStyle = {
  color: '#ddd',
  bold: true,
  underline: false,
}
```

**Comment by orballo** [comment]
Blocked until `converters` have `state` as a parameter.
