### ISSUE TITLE
Use fastdom to improve performance

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/saturn-theme#90]
https://github.com/wilsonpage/fastdom
https://developers.google.com/web/fundamentals/performance/rendering/avoid-large-complex-layouts-and-layout-thrashing

**Comment by luisherranz** [comment]
We'll add it on #36

**Comment by DAreRodz** [comment]
Closed at 327dc1971e35819f06d450bc7507c20367c82cf0.
